site_name: snekcord
site_description: A work-in-progress Discord API wrapper written in Python.
site_author: asleep-cult
theme:
  name: "material"

repo_name: asleep-cult/snekcord
repo_url: https://github.com/asleep-cult/snekcord

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference:
    - Objects:
      - Base: api_reference/objects/base.md
      - Channels: api_reference/objects/channels.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
