site_name: snekcord
site_description: A work-in-progress Discord API wrapper written in Python.
site_author: asleep-cult
theme:
  name: "material"
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

repo_name: asleep-cult/snekcord
repo_url: https://github.com/asleep-cult/snekcord

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
    - Objects:
      - Base: api-reference/objects/base.md
      - Channels: api-reference/objects/channels.md
      - Embed: api-reference/objects/embed.md
      - Guild: api-reference/objects/guild.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
